package io.github.smyrgeorge.ktkit.api.rest

import io.github.smyrgeorge.ktkit.api.error.ErrorSpecData
import io.github.smyrgeorge.ktkit.api.rest.openapi.OpenApiInfo
import io.github.smyrgeorge.ktkit.util.camelCaseToKebabCase
import kotlinx.serialization.Serializable

/**
 * Structured error response for API endpoints.
 *
 * This class is used to serialize errors in a consistent format for API responses.
 *
 * @property title Error code (typically the error type)
 * @property status HTTP status code associated with the error
 * @property detail The detailed error information
 * @property requestId Request ID for tracing
 * @property data Additional error deta
 *
 * Check here:
 * https://www.rfc-editor.org/rfc/rfc9457.html
 */
@Serializable
@OpenApiInfo("A problem details object (RFC 9457) — the error payload of all error responses.")
data class ApiError(
    @OpenApiInfo("A URI reference that identifies the problem type (\"about:blank\" when absent).")
    val type: String?,
    @OpenApiInfo("A short, human-readable summary of the problem type.")
    val title: String,
    @OpenApiInfo("The HTTP status code generated by the origin server for this occurrence of the problem.")
    val status: Int,
    @OpenApiInfo("A human-readable explanation specific to this occurrence of the problem.")
    val detail: String,
    // Extensions:
    @OpenApiInfo("The id of the request that produced the problem (extension member).")
    val requestId: String?,
    @OpenApiInfo("Additional problem-specific data (extension member).")
    val data: ErrorSpecData?
) {
    companion object {
        fun errorType(
            includeTypePropertyInApiError: Boolean,
            errorTypeHost: String,
            title: String
        ): String? {
            return if (includeTypePropertyInApiError) "${errorTypeHost}/${camelCaseToKebabCase(title)}"
            else null
        }
    }
}
