name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Maven Central
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Project
        uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5.7.0
        with:
          distribution: corretto
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Bootstrap ktkit Gradle plugin
        run: ./scripts/bootstrap.sh

      - name: Gradle Build
        run: ./gradlew build
